#!/bin/bash
#SBATCH --partition=queue
#SBATCH --time=14-00:00:00
#SBATCH -N 1 # Nodes
#SBATCH -n 1 # Tasks
#SBATCH --cpus-per-task=1
#SBATCH --error=%J.run_makeflows.err
#SBATCH --output=%J.run_makeflows.out

# Sponge Makeflows generated by
# /home/evan/marine_drugs/marine_drugs/src/make_sponge_makeflows.sh


makeflow --email=erees@wisc.edu --summary-log=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs/FL2014_3.summary.log --monitor=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs -T slurm /home/evan/marine_drugs/marine_drugs/src/features/FL2014_3.mf &
makeflow --email=erees@wisc.edu --summary-log=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs/FL2015_30.summary.log --monitor=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs -T slurm /home/evan/marine_drugs/marine_drugs/src/features/FL2015_30.mf &
makeflow --email=erees@wisc.edu --summary-log=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs/FL2015_34.summary.log --monitor=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs -T slurm /home/evan/marine_drugs/marine_drugs/src/features/FL2015_34.mf &
makeflow --email=erees@wisc.edu --summary-log=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs/FL2015_37.summary.log --monitor=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs -T slurm /home/evan/marine_drugs/marine_drugs/src/features/FL2015_37.mf &
makeflow --email=erees@wisc.edu --summary-log=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs/FL2015_42.summary.log --monitor=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs -T slurm /home/evan/marine_drugs/marine_drugs/src/features/FL2015_42.mf &
makeflow --email=erees@wisc.edu --summary-log=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs/FL2015_44.summary.log --monitor=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs -T slurm /home/evan/marine_drugs/marine_drugs/src/features/FL2015_44.mf &
makeflow --email=erees@wisc.edu --summary-log=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs/FL2015_4.summary.log --monitor=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs -T slurm /home/evan/marine_drugs/marine_drugs/src/features/FL2015_4.mf &
makeflow --email=erees@wisc.edu --summary-log=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs/FL2015_8.summary.log --monitor=/home/evan/marine_drugs/marine_drugs/data/interim/binning/logs -T slurm /home/evan/marine_drugs/marine_drugs/src/features/FL2015_8.mf &
wait
